### PR TITLE
Improve and refactor code

### LINKED ISSUE #21: PDO failed to parse address localhost:3306:3306
During the final step of installation, PDO can't connect to database. In `ajax.php`:

```php
new PDO("mysql:host=localhost:3306;dbname=...")
```

Causing `PDOException: SQLSTATE[HY000] [2002] Failed to parse address "localhost:3306:3306"`

This can be fixed by specific port in `port` parameter like this:

```php
new PDO("mysql:host=localhost;port=3306;dbname=...")
```

PHP Version 7.0.18-0ubuntu0.16.04.1

### PR DESCRIPTION
**Pull request by lion328**
- Merge multiple SQL query to one.
- Add helper functions for print error and debugging data.
- Change `else if` to `elseif`.
- Remove unnecessary `isset`.
- Fixes #21

### CODE REVIEW

**Comment by riflowth** [comment]
Thanks a lot. I will test it in soon. 😃 👍

**Comment by LazosPlaying** [comment]
I'd say that `isset($data)` is pretty useful, because when you want to test if a variable has a value, that variable must exist. If the variable does not exist, you'll start getting errors in the error log...

**Comment by lion328** [comment]
@LazosPlaying From description of `empty` function [here](https://secure.php.net/manual/en/function.empty.php): 

> No warning is generated if the variable does not exist. That means empty() is essentially the concise equivalent to !isset($var) || $var == false.

**Comment by LazosPlaying** [comment]
True, did not know that. Well.. better said, I forgot about it :/

Bad habits I guess..

**Comment by riflowth** [comment]
@lion328 Thanks a lot 😭 👍 👍 👍 👍

**Pull request merged**
